### ISSUE TITLE
Image export failed.

### ISSUE THREAD

**Issue by gmalenko** [aspose-cad/Aspose.CAD-for-.NET#3] opened 2017-12-05 20:19 UTC
I am trying to convert a DGN File.  
Here is my function so far

private static void ConvertDgnToPdf(Stream input, Stream output)
        {
            using (var cadImage = (CAD.FileFormats.Dgn.DgnImage)CAD.Image.Load(input))
            {
                var rasterizationOptions = new CAD.ImageOptions.CadRasterizationOptions();
                rasterizationOptions.PageWidth = 600;
                rasterizationOptions.PageHeight = 300;
                rasterizationOptions.CenterDrawing = true;
                rasterizationOptions.NoScaling = true;
                rasterizationOptions.AutomaticLayoutsScaling = false;
                CAD.ImageOptions.PdfOptions pdfOptions = new CAD.ImageOptions.PdfOptions();
                pdfOptions.VectorRasterizationOptions = rasterizationOptions;
                cadImage.Save(output, pdfOptions);
            }
    }

I am looking at the example [https://github.com/aspose-cad/Aspose.CAD-for-.NET/blob/master/Examples/CSharp/Exporting-DGN/ExportDGNToPdf.cs](https://github.com/aspose-cad/Aspose.CAD-for-.NET/blob/master/Examples/CSharp/Exporting-DGN/ExportDGNToPdf.cs) and I'm getting a "Image Export Failed".

What is missing?  I am using the Nikon dgn file as well.

Also, I believe that line 21 should be  **(Aspose.CAD.FileFormats.Dgn.DgnImage)** instead of ** (Aspose.CAD.FileFormats.Cad.CadImage)**.  It will result in a **Cannot cast 'Aspose.CAD.Image.Load(input)' (which has an actual type of 'Aspose.CAD.FileFormats.Dgn.DgnImage') to 'Aspose.CAD.FileFormats.Cad.CadImage'** error.

**Comment by mudassirfayyaz** [comment] 2017-12-06 14:58
@gmalenko,

I have observed the issue shared by you and like to share that the code sample in example is fine. There seems to be an issue with API while working with your DGN file. Can you please share the source DGN file reproducing issue on your end.

**Comment by gmalenko** [comment] 2017-12-06 15:38
@mudassirfayyaz 

Here are my example files.  Thank you for responding!
[example_files.zip](https://github.com/aspose-cad/Aspose.CAD-for-.NET/files/1535734/example_files.zip)

**Comment by aspose-cad** [comment] 2017-12-06 17:49
@gmalenko ,

Thank you for sharing the files. I have tested the files on my end and have received, "Image saving failed" exception. An issue with ID **CADNET-494** has been added in our issue tracking system to further investigate the issue and we will share updates with you as soon as the issue will be fixed.

**Comment by gmalenko** [comment] 2017-12-06 18:33
@aspose-cad 
Thank you

**Comment by gmalenko** [comment] 2018-02-05 19:01
@aspose-cad  any updates?

**Comment by aspose-cad** [comment] 2018-02-06 03:59
@gmalenko,

I have verified from our issue tracking system and like to share that concerned issue has been marked as resolved in upcoming Aspose.CAD for .NET 18.2, which will be available by end of February. We will share the good news with you as soon as the issue will be fixed.

**Closed as completed** 2019-03-04 20:29 UTC
